cabal-version: 3.0
name: circuits
version: 0.3.0.0
license: BSD-3-Clause
license-file: LICENSE
copyright: Tony Day (c) 2025-2026
category: control
author: Tony Day
maintainer: tonyday567@gmail.com
homepage: https://github.com/tonyday567/circuits#readme
bug-reports: https://github.com/tonyday567/circuits/issues
synopsis: first-class circuits
description:
  circuits provides a suite of tools that make coding with circuits first-class.

build-type: Simple
tested-with:
  ghc ==9.10.1
  ghc ==9.12.2
  ghc ==9.14.1

extra-doc-files:
  ChangeLog.md
  LICENSE
  readme.md

source-repository head
  type: git
  location: https://github.com/tonyday567/circuits

common ghc-options-stanza
  ghc-options:
    -Wall
    -Wno-unused-imports
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints

library
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: src
  exposed-modules:
    Circuit
    Circuit.Axioma.Test
    Circuit.Bimonoid
    Circuit.Body
    Circuit.Category
    Circuit.Cell
    Circuit.Container
    Circuit.Equip
    Circuit.Hyper
    Circuit.Linear
    Circuit.Machine
    Circuit.Net
    Circuit.Optic
    Circuit.Poly
    Circuit.Process
    Circuit.Pullback
    Circuit.Rel
    Circuit.Shared
    Circuit.Span
    Circuit.Stream
    Circuit.Syntax
    Circuit.Tensor
    Circuit.Trace
    Circuit.Traced

  build-depends:
    base >=4.20 && <5,
    these >=1.1 && <1.3,

executable circuits-axioma
  import: ghc-options-stanza
  default-language: GHC2024
  main-is: circuits-axioma.hs
  hs-source-dirs: app
  other-modules:
    Axioma.Bisim
    Axioma.Common
    Axioma.Container
    Axioma.Effect
    Axioma.Equip
    Axioma.FinRel
    Axioma.Machine
    Axioma.Optic
    Axioma.Poles
    Axioma.Process
    Axioma.Pullback
    Axioma.Shared
    Axioma.Span
    Axioma.Split

  build-depends:
    base >=4.20 && <5,
    circuits,
    optparse-applicative >=0.17 && <0.20,
    these >=1.1 && <1.3,
