name:                 traced
version:              0.1.0.0
visibility:           public
id:                   traced-0.1.0.0-inplace
key:                  traced-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            (c) 2026
maintainer:           tonyday567@gmail.com
author:               Anonymous
synopsis:             Free traced monoidal category
description:
    Traced is a GADT encoding the free traced monoidal category over
    Haskell functions. Three constructors defer three operations:
    Apply (fmap), Compose (composition), Untrace (fixed point).

    The library proves the tower of free constructions using equational
    reasoning: Coyoneda (free functor) → Free (free category) → Traced
    (free traced category). A unified GADT recovers all three levels.

category:             Control
abi:                  inplace
exposed:              True
exposed-modules:      Hyp Traced
import-dirs:
    /Users/tonyday567/repos/traced/dist-newstyle/build/aarch64-osx/ghc-9.14.1/traced-0.1.0.0/build

library-dirs:
    /Users/tonyday567/repos/traced/dist-newstyle/build/aarch64-osx/ghc-9.14.1/traced-0.1.0.0/build

library-dirs-static:
    /Users/tonyday567/repos/traced/dist-newstyle/build/aarch64-osx/ghc-9.14.1/traced-0.1.0.0/build

dynamic-library-dirs:
    /Users/tonyday567/repos/traced/dist-newstyle/build/aarch64-osx/ghc-9.14.1/traced-0.1.0.0/build

data-dir:             /Users/tonyday567/repos/traced/.
hs-libraries:         HStraced-0.1.0.0-inplace
depends:
    base-4.22.0.0-1f90 cntnrs-0.7-e2357059 mtl-2.3.1-c99f
    prfnctrs-5.6.3-acf6d799 ths-1.2.1-9b8cc8b5

haddock-interfaces:
    /Users/tonyday567/repos/traced/dist-newstyle/build/aarch64-osx/ghc-9.14.1/traced-0.1.0.0/doc/html/traced/traced.haddock

haddock-html:
    /Users/tonyday567/repos/traced/dist-newstyle/build/aarch64-osx/ghc-9.14.1/traced-0.1.0.0/doc/html/traced
